1. Create a vector with values ranging from 10 to 49.
2. Create a 3x3 matrix with values ranging from 0 to 8.
3. Create a 3x3 identity matrix.
4. Create a 3x3x3 array with random values.
5. Create a 10x10 array with random values and find the minimum and maximum values.
6. Create a random vector of size 30 and find the mean value.
7. Normalize a 5x5 random matrix.
8. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product).
9. Create two 3x3 matrices and compute their dot product.  
10. Given a 4x4 matrix, find its transpose.  
11. Create a 3x3 matrix and calculate its determinant.  
12. Create two matrices \( A \) (3x4) and \( B \) (4x3), and compute the matrix product \( A \cdot B \).  
13. Create a 3x3 random matrix and a 3-element column vector. Compute the matrix-vector product.  
14. Solve the linear system \( Ax = b \) where \( A \) is a 3x3 matrix, and \( b \) is a 3x1 column vector.  
15. Given a 5x5 matrix, find the row-wise and column-wise sums.

In [3]:
pip install numpy

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.2/5.2 MB 857.1 kB/s  0:00:06 eta 0:00:01
Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np

In [6]:
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [10]:
a3d = np.array([
    [0, 1, 2],
    [3, 4, 5],
    [6, 7, 8]
])

In [12]:
a3d.shape

(3, 3)

In [ ]:
np.eye(3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [17]:
arr = np.random.rand(3, 3, 3)
arr

array([[[0.7309402 , 0.90786749, 0.73355872],
        [0.71810539, 0.88439174, 0.34982395],
        [0.97938534, 0.86549003, 0.90539487]],

       [[0.88306367, 0.26450797, 0.91017759],
        [0.30631241, 0.86810161, 0.37262603],
        [0.69079166, 0.95037813, 0.21048128]],

       [[0.8042168 , 0.30310538, 0.4261053 ],
        [0.70068053, 0.21317439, 0.0574827 ],
        [0.12680079, 0.63432663, 0.36331991]]])

In [18]:
arr.shape

(3, 3, 3)

In [19]:
arr10 = np.random.rand(10, 10)
arr10

array([[0.40449167, 0.90501684, 0.34346305, 0.34043573, 0.86187685,
        0.26005643, 0.84497568, 0.54285018, 0.46607881, 0.15840828],
       [0.98769452, 0.26052396, 0.00982231, 0.45586881, 0.06959556,
        0.85101961, 0.108471  , 0.60205864, 0.19845423, 0.10536752],
       [0.02792436, 0.25011831, 0.28925765, 0.0249775 , 0.99801924,
        0.09111655, 0.7689718 , 0.52264557, 0.11743063, 0.62372808],
       [0.80047276, 0.64610759, 0.23158342, 0.81522497, 0.17858716,
        0.77179468, 0.605127  , 0.50617393, 0.29366277, 0.49676284],
       [0.73153522, 0.37414198, 0.41695258, 0.71860501, 0.20752401,
        0.2208801 , 0.350617  , 0.47742182, 0.95681153, 0.33061504],
       [0.02567977, 0.97985151, 0.51827987, 0.70627951, 0.42963274,
        0.04192406, 0.04206949, 0.22024886, 0.02967128, 0.09989185],
       [0.76952736, 0.9341552 , 0.19483635, 0.42691637, 0.80714746,
        0.84392884, 0.5326533 , 0.8948501 , 0.447559  , 0.11153602],
       [0.46933965, 0.61469637, 0.3417530

In [24]:
arr10.max()

np.float64(0.9980192381819238)

In [23]:
arr10.min()

np.float64(0.009822310337665341)

In [30]:
vect = np.random.rand(30)
vect

array([0.09228443, 0.48482853, 0.66965534, 0.72617264, 0.81691832,
       0.42299298, 0.27813792, 0.44140088, 0.27375178, 0.6122313 ,
       0.77250398, 0.3717274 , 0.41372973, 0.97220282, 0.41194503,
       0.37061465, 0.08025447, 0.23242491, 0.04876278, 0.32747645,
       0.95679812, 0.20824567, 0.24124931, 0.56234051, 0.6827539 ,
       0.31006769, 0.58086436, 0.33680097, 0.02850195, 0.54251023])

In [33]:
vect.mean()

np.float64(0.4423383016695855)

In [35]:
x = np.random.rand(5, 5)
xnorm = (x - x.min()) / (x.max() - x.min())
print(xnorm)

[[0.92048104 0.16731012 0.         0.12051484 0.01973798]
 [0.71300171 0.41498883 0.26823148 0.66172521 0.20681565]
 [0.52312041 0.79115499 0.8766304  0.28255017 0.36926292]
 [0.97803832 0.91522036 0.33575887 0.35861387 0.68260973]
 [0.97835174 0.86737688 0.98129468 1.         0.11419321]]


In [41]:
A = np.random.randint(0, 6, (5, 3))
B = np.random.randint(0, 6, (3, 2))

C = A @ B
print(C)

[[ 3  8]
 [ 1  4]
 [ 4  8]
 [ 4 16]
 [ 3  8]]


In [46]:
D = np.random.randint(0, 6, (3, 3))
E = np.random.randint(0, 6, (3, 3))

F = D.dot(E)
F

array([[24, 22, 26],
       [25, 37, 29],
       [28, 35, 19]])

In [47]:
D = np.random.randint(0, 6, (4, 4))
D

array([[2, 0, 2, 1],
       [1, 2, 5, 1],
       [3, 0, 0, 2],
       [2, 2, 5, 5]])

In [48]:
D.T

array([[2, 1, 3, 2],
       [0, 2, 0, 2],
       [2, 5, 0, 5],
       [1, 1, 2, 5]])

In [49]:
D = np.random.randint(0, 6, (3, 3))
D

array([[3, 3, 5],
       [4, 5, 3],
       [2, 0, 1]])

In [50]:
np.linalg.det(D)

np.float64(-29.000000000000004)

In [53]:
A = np.random.randint(0, 6, (3, 4))
B = np.random.randint(0, 6, (4, 3))

F = A @ B
F

array([[30, 24, 28],
       [40, 34, 41],
       [45, 32, 19]])

In [54]:
D = np.random.randint(0, 6, (3, 3))
V = np.random.randint(0, 6, (3))
V


array([5, 0, 5])

In [55]:
D * V

array([[ 0,  0,  5],
       [ 0,  0,  5],
       [15,  0, 10]])

In [ ]:
A = np.random.randint(0, 6, (5, 3))
B = np.random.randint(0, 6, (3, 2))

C = A @ B
print(C)

[[ 3  8]
 [ 1  4]
 [ 4  8]
 [ 4 16]
 [ 3  8]]


In [56]:
D = np.random.randint(0, 6, (3, 3))
V = np.random.randint(0, 6, (3, 1))

X = np.linalg.solve(D, V)
X

array([[ 1.25      ],
       [-1.66666667],
       [ 2.75      ]])

In [57]:
A = np.random.randint(0, 6, (5, 5))
A

array([[0, 0, 5, 2, 2],
       [4, 1, 2, 0, 5],
       [4, 1, 4, 1, 2],
       [4, 0, 2, 4, 5],
       [0, 0, 4, 4, 2]])

In [58]:
rows_sums = A.sum(axis=1)
rows_sums

array([ 9, 12, 12, 15, 10])

In [60]:
column_sums = A.sum(axis=0)
column_sums

array([12,  2, 17, 11, 16])